name: Frontend Continuous Integration

on:
  push:
    branches:    
      - main
  workflow_dispatch:

env: 
  NODE_VERSION: 18
  WORK_DIR: starter/frontend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      # Checkout code
    - name: Checkout
      uses: actions/checkout@v3

      # Setup NodeJS
      # Perform a cache action to restore cache before dependency install
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION}}
        cache: 'npm'
        cache-dependency-path: "${{ env.WORK_DIR }}/package.json"

      # Install dependencies
    - name: Install dependencies
      run: cd ${{ env.WORK_DIR }} && npm ci

      # Lint
    - name: Lint
      run: cd ${{ env.WORK_DIR }} && npm run lint
  
  test:
    runs-on: ubuntu-latest
    steps: 

      # Checkout code
    - name: Checkout
      uses: actions/checkout@v4

      # Setup NodeJS
      # Perform a cache action to restore cache before dependency install
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION}}
        cache: 'npm'
        cache-dependency-path: "${{ env.WORK_DIR }}/package.json"

      # Install dependencies
    - name: Install dependencies
      run: cd ${{ env.WORK_DIR }} && npm ci

      # Test
    - name: Test
      run: |
        cd ${{ env.WORK_DIR }} 
        npm run test

  build:
    runs-on: ubuntu-latest
    needs:
    - lint
    - test
    steps: 

      # Checkout code
    - name: Checkout
      uses: actions/checkout@v4

    - name: Change to work directory
      run: cd ${{ env.WORK_DIR }}

      # Build
    - name: Build 
      run: |
        cd ${{ env.WORK_DIR }}
        docker build -f Dockerfile .